# Generated by Django 3.1.7 on 2021-04-30 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20210429_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipping',
            name='zipcode',
            field=models.CharField(max_length=200),
        ),
    ]
